Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-06, with the labels that each got.

#1051 Add type of campaign next to its name
  _dev/.storybook/mock/campaigns-list.js
  _dev/src/assets/scss/app.scss
  _dev/src/assets/scss/components/_badge.scss
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
  _dev/src/enums/reporting/CampaignStatus.ts
Labels: enhancement, VueJS

#1055 Fix only display disapproved products in product feed status details
  _dev/.storybook/mock/product-feed.js
  _dev/src/components/product-feed-page/product-feed-status-details.spec.ts
  _dev/src/components/product-feed-page/product-feed-table-status-details-row.vue
  _dev/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/stories/product-feed-table-status-details.stories.ts
Labels: bug, VueJS

#1062 Change header with tooltip prescan table
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: enhancement, VueJS

#1065 Banner campaign : change wording and cta
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/banner-campaigns.vue
Labels: enhancement, VueJS

#1064 Add type to campaign object on post and on store
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
Labels: Feature, VueJS

#1047 Create PMax modal
  _dev/src/assets/json/googleUrl.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  _dev/src/enums/pmax/pmax-modal.ts
  _dev/src/views/onboarding-page.vue
  _dev/stories/pmax-discover-popin.stories.ts
Labels: Feature, VueJS

#1067 Fix path to translation file
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: bug, VueJS

#1069 Fix translation : missing letter
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#1070 Change campaign type to PMAX on post
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
Labels: Feature, VueJS

#1058 Add banner on form creation pmax
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.spec.ts
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/router/index.ts
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: Feature, VueJS

#1076 Bump to v1.21.0
  psxmarketingwithgoogle.php
Labels: enhancement, PHP

#1078 Creation of a banner to inform merchants of pmax
  _dev/src/App.vue
  _dev/src/assets/scss/base/_common.scss
  _dev/src/assets/scss/components/_helper-shopid.scss
Labels: enhancement, VueJS

#1080 Add illustations on modals pmax
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-en.svg
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-en.svg
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-en.svg
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
Labels: VueJS

#1081 Adding the wording for the banner
  _dev/src/assets/json/translations/en/ui.json
Labels: enhancement

#1085 Add new illustration for Pmax modal
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-en.svg
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-en.svg
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-en.svg
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
Labels: enhancement, VueJS

#1073 Add storybook's story on error API creation campaign
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: VueJS

#1089 Change route params to redirect to pmax on campaign creation
  _dev/src/components/commons/banner-campaigns.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/router/index.ts
Labels: enhancement, VueJS

#1053 Update composer.json for distribution via packagist
  composer.json
Labels: enhancement, PHP

#1090 Update wording smart shopping campaign card
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/onboarding/section-title.vue
  _dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
  _dev/src/views/onboarding-page.vue
Labels: Feature, VueJS

#1097 Modify wording from SSC to PMAX
  _dev/src/assets/json/translations/en/ui.json
Labels: enhancement, VueJS

#1099 Update wording landing and configuration pages + banner
  _dev/src/App.vue
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
Labels: enhancement, VueJS

#1100 Add new images & change text in modal
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-ES.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-coming-soon-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-pmax-released-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-PL.png
  _dev/src/assets/json/googleUrl.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  _dev/src/enums/pmax/pmax-modal.ts
  _dev/src/views/onboarding-page.vue
  _dev/stories/pmax-discover-popin.stories.ts
Labels: VueJS

#1103 Adding banner to inform merchand for PMAX release
  _dev/src/App.vue
  _dev/src/assets/scss/base/_common.scss
  _dev/src/assets/scss/components/_helper-shopid.scss
Labels: VueJS

#1105 Display PMax modal when api call is ended
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  _dev/src/views/onboarding-page.vue
Labels: VueJS

#1114 Revert translations about PMax
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
Labels: bug, VueJS

#1115 Modify wording on modal & add storybook test
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  _dev/stories/pmax-discover-popin.stories.ts
Labels: waiting for PM, VueJS

#1123 Fix CI
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
Labels: bug, VueJS

#1124 Fix pictures URLs that were not using the CDN
  _dev/vue.config.js
Labels: bug, VueJS

#1126 Fix loader on campaign list
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
Labels: VueJS

#1127 Re-enable NPM cache in workflow
  .github/workflows/build-release.yml
  .github/workflows/chromatic.yml
  .github/workflows/js.yml
  .github/workflows/publish.yml
Labels: enhancement, VueJS

#1131 Update wording for app versions and remove accounts healthcheck link
  _dev/src/store/modules/app/state.ts
  _dev/src/views/debug.vue
  controllers/admin/AdminAjaxPsxMktgWithGoogleController.php
Labels: enhancement, PHP, VueJS

#1128 Show campaign type dropdown as disabled when there is only one type of campaign available
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
Labels: enhancement, VueJS

#1130 Fix the carriage return for campaigns without link in reporting tab
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
Labels: bug, VueJS

#1133 Update wording
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
  _dev/src/components/help/faq.vue
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  psxmarketingwithgoogle.php
Labels: enhancement, PHP, VueJS

#1135 Display Youtube video on the Help tab
  _dev/src/components/help/faq.vue
Labels: Feature, VueJS

#1138 Reuse Help tab name in panel title
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
  _dev/src/components/help/faq.vue
Labels: enhancement, VueJS

#1140 Fix responsiveness of PMax modal
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
Labels: bug, VueJS
