Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-02, with the labels that each got.

#842 Do not wait for campaign filters to load before displaying ssc list
  _dev/src/views/campaign-page.vue
Labels: bug, VueJS

#843 Run all initial actions of campaign page in parallel when possible
  _dev/src/views/campaign-page.vue
Labels: bug, VueJS

#845 Add error handling on filters fetching to update user
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-dimension.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: bug, VueJS

#846 Redesign of the product feed page
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/app.scss
  _dev/src/assets/scss/base/_border.scss
  _dev/src/assets/scss/base/_typography.scss
  _dev/src/assets/scss/components/_sync-history.scss
  _dev/src/components/product-feed-page/submitted-products/products-status-card.vue
  _dev/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/src/components/product-feed-page/sync-history/sync-history.vue
  _dev/src/components/product-feed-page/sync-history/sync-state.vue
  _dev/src/components/product-feed-page/sync-overview.vue
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/enums/product-feed/products-status-type.ts
  _dev/src/enums/product-feed/sync-history.ts
  _dev/stories/product-feed-card.stories.ts
  _dev/stories/product-feed-overview.stories.ts
Labels: VueJS

#851 Fix product feed overview after design review
  _dev/src/assets/scss/base/_color.scss
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/product-feed-page/submitted-products/products-status-card.vue
  _dev/src/components/product-feed-page/sync-overview.vue
Labels: VueJS

#847 Modify translation and round conversion number on reporting page
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
  _dev/src/components/smart-shopping-campaign/reporting/products-performance/products-performance-table-row.vue
Labels: bug, VueJS

#849 Refactors shipping setting to have header cell hoverable
  _dev/src/components/product-feed/settings/shipping-settings/shipping-settings.vue
Labels: enhancement, VueJS

#858 Add limit for handlingTime in shippingSettings
  _dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.spec.ts
  _dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.vue
Labels: bug, VueJS

#861 Check new error code in case of API problem
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
Labels: bug, VueJS

#862 Add condition for get only one country for productFeed
  _dev/src/components/commons/select-country.vue
Labels: bug, VueJS

#870 FIX : display date problem in product feed settings summary
  _dev/src/components/commons/badge-list-requirements.vue
  _dev/src/components/commons/progress-ring.vue
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/src/components/product-feed/product-feed-card-next-sync-card.vue
  _dev/src/components/product-feed/product-feed-card-report-card.vue
  _dev/src/components/product-feed/product-feed-card-report-mapped-categories-card.vue
  _dev/src/components/product-feed/product-feed-card-report-products-card.vue
  _dev/src/components/product-feed/product-feed-card-report-products-sync-card.vue
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/commons/actions-buttons.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
Labels: bug, VueJS

#871 New events segment
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
  _dev/src/views/onboarding-page.vue
Labels: VueJS

#865 Improvement : Filters : Display number of products
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-confirm-cancel.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-filter.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/utils/SSCFilters.ts
Labels: VueJS
