Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-09, with the labels that each got.

#1196 Go on integrating Step 2 - Option 2
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/src/store/modules/product-feed/actions.ts
Labels: enhancement, VueJS

#1195 Feat: Add new step 2 - Method 1
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/base/_common.scss
  _dev/src/assets/scss/components/_button.scss
  _dev/src/components/campaign-creation/campaign-creation.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
  _dev/src/enums/product-feed/offer.ts
  _dev/src/enums/product-feed/rate.ts
  _dev/src/providers/shipping-rate-provider.spec.ts
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/app/getters-types.ts
  _dev/src/store/modules/app/getters.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/stories/product-feed-settings.stories.ts
Labels: Feature, VueJS

#1198 Display countries while importing shipping settings only if they have one associated carrier
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
  _dev/src/utils/LocalStorage.ts
  _dev/stories/product-feed-settings.stories.ts
Labels: enhancement, VueJS

#1199 Implement validation system on both options of shipping configuration
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/src/providers/shipping-settings-provider.spec.ts
  _dev/src/providers/shipping-settings-provider.ts
Labels: enhancement, VueJS

#1201 Fix undefined refreshComponent method
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
Labels: bug, VueJS

#1202 Implement switch to flat rate from import method
  _dev/jest.config.js
  _dev/package-lock.json
  _dev/package.json
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
Labels: enhancement, VueJS

#1200 Start deprecating old attribute autoImportShippingSettings
  _dev/.storybook/mock/product-feed.js
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: enhancement, VueJS

#1203 Management of localStorage for estimate method
  _dev/.storybook/mock/product-feed.js
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: VueJS

#1206 Warn merchants that missing shipping settings must now be provided
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/store/modules/product-feed/getters.ts
  _dev/stories/product-feed-card.stories.ts
Labels: enhancement, VueJS

#1207 Update colors of selected option in shipping setup step
  _dev/.storybook/mock/product-feed.js
  _dev/.storybook/mock/product-feed.ts
  _dev/package-lock.json
  _dev/package.json
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/app.scss
  _dev/src/assets/scss/components/_shipping_setup.scss
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/components/product-feed/settings/commons/actions-buttons.vue
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.spec.ts
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/providers/shipping-settings-provider.spec.ts
  _dev/src/store/modules/product-feed/index.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: enhancement, VueJS

#1212 Add management of API response & change naming
  _dev/.storybook/mock/product-feed.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/enums/product-feed/rate.ts
  _dev/src/providers/shipping-rate-provider.spec.ts
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/LocalStorage.ts
Labels: VueJS

#1208 Integrate summary with new shipping settings
  _dev/.storybook/mock/product-feed.ts
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/components/_productfeedreportcard.scss
  _dev/src/components/product-feed/product-feed-card-report-card.vue
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/summary/summary.spec.ts
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
  _dev/stories/product-feed-settings.stories.ts
  _dev/stories/product-feed-summary-cards.stories.ts
Labels: enhancement, VueJS

#1214 Fix state initialization
  _dev/src/store/modules/accounts/index.ts
  _dev/src/store/modules/app/index.ts
Labels: bug, VueJS

#1215 Fix access to array
  _dev/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1216 Add unit tests on Target Countries component
  _dev/.storybook/mock/state-app.ts
  _dev/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
Labels: enhancement, VueJS

#1217 Save step when merchant won't finish productFeed
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/LocalStorage.ts
Labels: PM ✔️, bug, VueJS

#1219 Change translations on summary step & change default value for estimate step
  _dev/src/components/product-feed/settings/sync-schedule/sync-schedule.vue
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/mutations.ts
Labels: VueJS

#1218 Add unit tests for Step 2 of Product feed funnel (Import option)
  _dev/package-lock.json
  _dev/package.json
  _dev/src/components/campaign-creation/campaign-creation.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
  _dev/stories/product-feed-settings.stories.ts
  _dev/tests/init.ts
Labels: enhancement, VueJS

#1222 Add unit test for estimate step
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
Labels: VueJS

#1224 Improve stories and mocks by using TypeScript
  _dev/.storybook/mock/campaigns-list.js
  _dev/.storybook/mock/campaigns-list.ts
  _dev/.storybook/mock/campaigns.js
  _dev/.storybook/mock/campaigns.ts
  _dev/.storybook/mock/free-listing.ts
  _dev/.storybook/mock/google-account.js
  _dev/.storybook/mock/google-account.ts
  _dev/.storybook/mock/google-ads.ts
  _dev/.storybook/mock/merchant-center-account.ts
  _dev/.storybook/mock/ps-accounts.ts
  _dev/.storybook/mock/shipping-settings-heavy.ts
  _dev/.storybook/mock/shipping-settings.ts
  _dev/.storybook/mock/state-accounts.js
  _dev/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/src/components/campaign/campaign-table-list.spec.ts
  _dev/src/providers/shipping-settings-provider.ts
  _dev/src/store/modules/campaigns/state.ts
  _dev/src/store/modules/google-ads/state.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/SSCFilters.spec.ts
  _dev/stories/banners-ads-overviews.stories.ts
  _dev/stories/free-listing-card.stories.ts
  _dev/stories/key-metrics.stories.ts
  _dev/stories/product-feed-settings.stories.ts
  _dev/stories/ps-account-card.stories.ts
  _dev/stories/reporting-daily-results-chart.stories.ts
  _dev/stories/smart-shopping-campaign-card.stories.ts
  _dev/stories/smart-shopping-campaign-creation.stories.ts
  _dev/stories/smart-shopping-campaign-table-list.stories.ts
Labels: enhancement, VueJS

#1229 Add validation on first step
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.spec.ts
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
Labels: enhancement, VueJS

#1230 Fix display of summary of product feed with old data
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
  _dev/stories/product-feed-card.stories.ts
Labels: bug, VueJS

#1231 Update default view when there is no country selected
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
Labels: enhancement, VueJS

#1232 Update wording
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.spec.ts
Labels: enhancement, VueJS

#1235 Fix loading of carriers that come from the previous version of product feed
  _dev/src/providers/shipping-settings-provider.ts
Labels: bug, VueJS

#1227 Apply feedback from tests
  _dev/.storybook/mock/product-feed.ts
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
  _dev/src/providers/shipping-rate-provider.spec.ts
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/shims-tsx.d.ts
  _dev/src/store/modules/app/getters.ts
  _dev/src/store/modules/app/index.ts
  _dev/src/store/modules/app/state.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: VueJS

#1238 Use warmup method on product feed funnel
  _dev/src/views/tunnel-product-feed.vue
Labels: bug, VueJS

#1237 Reload properly default target countries when reloading page on step 2
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
Labels: bug, VueJS

#1239 Resolve targetCountries saving problem
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
Labels: VueJS

#1240 Bump requested installed version of module to v1.24.0
  _dev/.env
Labels: enhancement, VueJS

#1241 Add detection of module version for very old modules
  _dev/src/components/commons/alert-update-module.vue
Labels: enhancement, VueJS

#1244 Change font for step 2 on productFeed
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
Labels: VueJS

#1242 Change wording for button when merchant start productFeed configuration
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.vue
Labels: enhancement, VueJS

#1247 Resolve UX problem on import carriers & modify wording
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
Labels: VueJS

#1248 Modify wording for step delivery & rate
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
Labels: VueJS

#1246 Allow to start again a specific step from the configuration page
  _dev/src/components/commons/stepper.spec.ts
  _dev/src/components/commons/stepper.vue
  _dev/src/components/product-feed/product-feed-stepper.vue
  _dev/stories/product-feed-card.stories.ts
Labels: bug, VueJS

#1252 Save the current position of stepper inside funnel
  _dev/src/components/product-feed/product-feed-settings.vue
Labels: VueJS

#1253 Improve ways to identify a current session for conversion actions
  classes/Buffer/TemplateBuffer.php
  classes/Handler/RemarketingHookHandler.php
Labels: bug, PHP

#1254 Revert "Save the current position of stepper inside funnel"
  _dev/src/components/product-feed/product-feed-settings.vue
Labels: VueJS

#1255 Fix initial value of target countries after refresh
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
Labels: bug, VueJS

#1257 Resolve stepper inside productFeed funnel
  _dev/src/components/product-feed/product-feed-settings.vue
Labels: VueJS

#1258 Fix an issue making all carriers enabled
  _dev/src/providers/shipping-settings-provider.ts
Labels: bug, VueJS

#1259 Restore wording when merchant start productFeed on stepper
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.vue
Labels: VueJS

#1262 Fix z index of tabs & allow override of their style
  _dev/src/App.vue
  _dev/src/assets/scss/layouts/_sticky-head.scss
Labels: enhancement, VueJS

#1263 Run Unit tests on different versions of PHP
  .github/workflows/php.yml
Labels: enhancement, PHP
