Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-03, with the labels that each got.

#856 Refacto vue router
  _dev/src/App.vue
  _dev/src/components/commons/stepper.spec.ts
  _dev/src/components/commons/stepper.vue
  _dev/src/components/landing-page/landing-page-footer.spec.ts
  _dev/src/components/landing-page/landing-page-footer.vue
  _dev/src/components/landing-page/landing-page-header.spec.ts
  _dev/src/components/landing-page/landing-page-header.vue
  _dev/src/components/product-feed/product-feed-card-report-card.vue
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/product-feed-popin-cancel.vue
  _dev/src/components/product-feed/product-feed-settings.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/components/product-feed/settings/shipping-settings/shipping-settings.vue
  _dev/src/components/product-feed/settings/summary/summary.spec.ts
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/components/product-feed/settings/sync-schedule/sync-schedule.vue
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/reporting/key-metrics/key-metrics-block.vue
  _dev/src/components/smart-shopping-campaign/reporting/key-metrics/key-metrics-period-selector.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/enums/product-feed/product-feed-settings-pages.ts
  _dev/src/enums/product-feed/product-feed-settings-steps.ts
  _dev/src/router/index.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/views/campaign-page.vue
  _dev/src/views/configuration.vue
  _dev/src/views/landing-page.vue
  _dev/src/views/multistore.vue
  _dev/src/views/reporting-page.vue
Labels: Feature, VueJS

#868 Refacto : pagination on campaigns performance's list
  _dev/src/components/commons/page-number-selector.vue
  _dev/src/components/commons/result-number-selector.vue
  _dev/src/components/commons/table-page-controls.vue
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table.vue
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
  _dev/stories/campaigns-performance-table.stories.ts
Labels: Feature, VueJS

#878 Missing refresh message after user action
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/alert-update-module.vue
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
Labels: bug, VueJS

#875 Update wording
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#881 Fix: add loader displaying while waiting for dimensions in popin filters SSC
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-dimension.vue
Labels: bug, VueJS

#882 Fix : Change behaviour if user go back in filters
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-confirm-cancel.vue
Labels: bug, VueJS

#883 Fix: load campaigns to find the one to edit
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: bug, VueJS

#869 add filter to avoid to send shipping not configured
  _dev/src/providers/shipping-settings-provider.spec.ts
  _dev/src/providers/shipping-settings-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
Labels: VueJS

#884 Feature : new api route to retrieve number of invalid products from prescan
  _dev/.storybook/mock/product-feed.js
  _dev/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/src/store/modules/product-feed/actions-types.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/views/product-feed-page.vue
  _dev/stories/product-feed-page.stories.ts
Labels: Feature, VueJS

#889 Rename state property for the number of products ready to sync
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions-types.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/views/campaign-page.vue
  _dev/src/views/tunnel-product-feed.spec.ts
  _dev/src/views/tunnel-product-feed.vue
Labels: enhancement, VueJS

#895 Fix redirection to landing page
  _dev/src/views/configuration.vue
  _dev/src/views/multistore.vue
Labels: bug, VueJS

#901 Suggest default Smart Shopping Campaign budget
  _dev/.env
  _dev/.gitignore
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/store/modules/app/state.ts
Labels: enhancement, VueJS

#900 Fix loading of campaign form after a refresh
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
Labels: bug, VueJS

#898 Define app build version to ease debugging
  .github/workflows/cdn.yml
  _dev/src/utils/Sentry.ts
  _dev/src/views/debug.vue
Labels: enhancement, VueJS

#902 Fix : Connect accounts on refresh reporting tab
  _dev/src/views/reporting-page.vue
Labels: bug, VueJS

#905 Fix : Connect accounts on refresh product feed tab
  _dev/src/views/product-feed-page.vue
Labels: bug, VueJS

#904 Fix : Connect accounts on refresh campaign tab
  _dev/src/views/campaign-page.vue
Labels: bug, VueJS

#873 Fix search feature on campaign product filters popin
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-confirm-cancel.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-filter.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
  _dev/src/utils/SSCFilters.spec.ts
  _dev/src/utils/SSCFilters.ts
  _dev/src/views/campaign-page.vue
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: bug, VueJS

#906 Refacto : create new action on refresh tabs
  _dev/src/store/modules/accounts/actions-types.ts
  _dev/src/store/modules/accounts/actions.ts
  _dev/src/views/campaign-page.vue
  _dev/src/views/product-feed-page.vue
  _dev/src/views/reporting-page.vue
Labels: enhancement, VueJS

#910 Rename interface for prescan
  _dev/src/store/modules/product-feed/state.ts
Labels: bug, VueJS

#891 Integration : banners ads
  _dev/.storybook/mock/google-ads.js
  _dev/src/assets/images/banner/ads-dollars.svg
  _dev/src/assets/images/banner/ads-euro.svg
  _dev/src/assets/images/banner/ads-poland.svg
  _dev/src/assets/images/banner/ads-pounds.svg
  _dev/src/assets/images/banner/dots.png
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/banner-ads.vue
  _dev/src/components/commons/banner-campaigns.vue
  _dev/src/components/google-ads-account/google-ads-account-popin-new.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
  _dev/src/utils/ImageFromCurrency.spec.ts
  _dev/src/utils/ImageFromCurrency.ts
  _dev/src/views/landing-page.spec.ts
  _dev/src/views/landing-page.vue
  _dev/stories/banners-ads-overviews.stories.ts
  _dev/stories/banners.stories.ts
  _dev/stories/onboarding-page.stories.ts
Labels: Feature, VueJS

#915 Check claiming and verify before trigger alert module disabled
  _dev/src/store/modules/accounts/actions.ts
Labels: VueJS

#913 Implementation ads banner on every card
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/banner-ads.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
  _dev/src/views/landing-page.vue
  _dev/stories/banners-ads-overviews.stories.ts
Labels: Feature, VueJS

#914 Resolve pagination for pre-validation scan
  _dev/src/assets/scss/layouts/_table.scss
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/src/store/modules/product-feed/actions.ts
Labels: VueJS

#917 Add new sentence for multi synchro
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions.ts
Labels: VueJS

#919 Add hook for destroy listener when leaving page
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table.vue
Labels: bug, VueJS

#922 Update eventbus version to 1.7.0
  _dev/.env
Labels: enhancement, VueJS

#924 Fix typo
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#926 Using another method for solve multiple API call on pagination
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table.vue
Labels: bug

#927 Sort lang on prevalidation scan table
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: bug, VueJS

#931 Remove duplicate for syncSchedule on productFeed
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: bug, VueJS

#928 Fix: display banner in campaign page + filters
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/utils/SSCFilters.ts
Labels: bug, VueJS

#933 Hide banner for Google Ads campaigns when module not fully configured
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/components/smart-shopping-campaign/smart-shoppinh-campaign-table-list.spec.ts
Labels: bug, VueJS

#934 Fix display of campaigns list title + złoty iso-code
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/utils/ImageFromCurrency.spec.ts
  _dev/src/utils/ImageFromCurrency.ts
  _dev/src/utils/PriceFromCurrency.spec.ts
  _dev/src/utils/PriceFromCurrency.ts
  _dev/stories/banners-ads-overviews.stories.ts
Labels: bug, VueJS

#935 Fix badge UI & align pagination of pre-scan
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/commons/table-page-controls.vue
Labels: bug, VueJS

#936 Fix the size of badge
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: VueJS

#938 Fix/UX : change image in popin configured
  _dev/src/assets/images/configured.png
  _dev/src/assets/images/configured.svg
  _dev/src/components/commons/popin-configured.vue
Labels: bug, VueJS

#939 Remove bracket on description on pre-validation scan page
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: enhancement, VueJS

#940 Change the navbar size
  _dev/src/assets/scss/layouts/_sticky-head.scss
Labels: enhancement, VueJS

#942 Check "no adult content" option by default
  _dev/src/components/merchant-center-account/website-requirements/step-store-info.vue
Labels: enhancement, VueJS

#937 Fix storybook mock
  _dev/.storybook/mock/product-feed.js
  _dev/.storybook/mock/smart-shopping-campaigns.js
  _dev/src/components/product-feed/settings/summary/summary.spec.ts
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/stories/product-feed-settings.stories.ts
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: bug, VueJS

#948 Solve problem when sync is failed on product feed page
  _dev/src/components/product-feed-page/sync-history/sync-history.vue
Labels: VueJS

#943 Add condition to display default phone number on phone verification popin after reloading page
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
Labels: VueJS

#945 UI - Wording : button export feed
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.spec.ts
Labels: VueJS

#947 Translate module description
  translations/de.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: enhancement, PHP

#952 Tracking : add 2 new segment events
  _dev/src/components/commons/banner-campaigns.vue
  _dev/src/components/commons/popin-configured.vue
Labels: VueJS

#944 Rework UI of the landing page
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/landing-page/landing-page-content.vue
  _dev/src/components/landing-page/landing-page-footer.vue
  _dev/src/components/landing-page/landing-page-header.vue
  _dev/src/views/landing-page.vue
Labels: enhancement, VueJS
