Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-11, with the labels that each got.

#1277 Merge all cards of the same step
  _dev/src/assets/scss/components/_onboardingcard.scss
  _dev/src/components/google-account/google-account-card.spec.ts
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/views/onboarding-page.vue
Labels: enhancement, VueJS

#1268 Switch on analytics-next to avoid conflicts on SMB
  _dev/.storybook/preview.js
  _dev/package-lock.json
  _dev/package.json
  _dev/src/App.vue
  _dev/src/lib/segment/index.ts
  _dev/src/main.ts
  _dev/src/views/onboarding-page.vue
Labels: enhancement, VueJS

#1280 Fix PS Accounts on Storybook
  _dev/.storybook/mock/ps-accounts.ts
  _dev/.storybook/preview-head.html
  _dev/.storybook/preview.js
  _dev/src/views/onboarding-page.vue
  _dev/stories/general-errors.stories.ts
  _dev/stories/onboarding-page.stories.ts
  _dev/stories/ps-account-card.stories.ts
Labels: bug, VueJS

#1283 Changing google Ads card for 2panel
  _dev/src/assets/images/ads-marketing.svg
  _dev/src/assets/images/boost-campaing.svg
  _dev/src/assets/images/local-offer.svg
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/campaigns/campaign-card.vue
  _dev/src/components/campaigns/campaign-tracking.vue
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.spec.ts
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/views/onboarding-page.vue
  _dev/stories/smart-shopping-campaign-card.stories.ts
Labels: VueJS

#1278 Rework step 2 with 2-panels design
  _dev/src/assets/images/google-merchant-center-icon-grey.svg
  _dev/src/assets/images/product-feed-icon-grey.png
  _dev/src/assets/images/product-feed-icon.png
  _dev/src/assets/images/product-feed-icon.svg
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/components/_onboardingcard.scss
  _dev/src/components/commons/badge-list-requirements.spec.ts
  _dev/src/components/commons/badge-list-requirements.vue
  _dev/src/components/free-listing/free-listing-card.spec.ts
  _dev/src/components/free-listing/free-listing-card.vue
  _dev/src/components/google-account/google-account-card.spec.ts
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/components/merchant-center-account/merchant-center-account-card.spec.ts
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/src/components/product-feed/product-feed-card-report-card.vue
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/product-feed-settings.vue
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
  _dev/stories/badge-list-requirements.stories.ts
  _dev/stories/free-listing-card.stories.ts
  _dev/stories/product-feed-card.stories.ts
  _dev/stories/ps-account-card.stories.ts
Labels: enhancement, VueJS

#1284 Add responsive on onboarding page
  _dev/src/views/onboarding-page.vue
Labels: VueJS

#1286 Update stepper to have a vertical version
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/components/_stepper.scss
  _dev/src/components/commons/stepper.vue
  _dev/src/components/product-feed/product-feed-stepper.vue
  _dev/stories/stepper.stories.ts
Labels: enhancement, VueJS

#1293 Changes from beedback of beta.3
  _dev/.storybook/assets/shame.css
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/product-feed-card.spec.ts
  _dev/src/components/product-feed/product-feed-card.vue
Labels: bug, VueJS

#1296 Remove duplicated text about CSS
  _dev/src/components/campaigns/campaign-card.vue
Labels: bug, VueJS

#1298 Always display tabs in menu except on landing page
  _dev/src/App.vue
Labels: enhancement, VueJS

#1299 Fix display of loading states
  _dev/src/assets/scss/components/_onboardingcard.scss
  _dev/src/assets/scss/vendors/_bootstrap-vue.scss
Labels: bug, VueJS

#1310 Changes from feedback of beta.8
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
  _dev/src/assets/scss/components/_stepper.scss
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
  _dev/src/views/onboarding-page.vue
Labels: bug, VueJS

#1311 Update UI-kit colors and style
  _dev/src/assets/images/boost-campaing.svg
  _dev/src/assets/images/local-offer.svg
  _dev/src/assets/images/product-feed-icon.svg
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/app.scss
  _dev/src/assets/scss/base/_border.scss
  _dev/src/assets/scss/base/_color.scss
  _dev/src/assets/scss/components/_badge.scss
  _dev/src/assets/scss/components/_button.scss
  _dev/src/assets/scss/components/_faq.scss
  _dev/src/assets/scss/components/_onboardingcard.scss
  _dev/src/assets/scss/pages/_attribute-mapping.scss
Labels: enhancement, waiting for UX, VueJS

#1316 Avoid conflicts with SMB Segment
  _dev/src/lib/segment/index.ts
Labels: bug, VueJS

#1314 Changes from feedback of beta.9
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/base/_common.scss
  _dev/src/assets/scss/components/_product-category-checkbox.scss
  _dev/src/assets/scss/components/_shipping_setup.scss
  _dev/src/assets/scss/layouts/_form.scss
  _dev/src/assets/scss/layouts/_table.scss
  _dev/src/components/campaign/reporting/key-metrics/key-metrics-period-selector.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/src/views/not-configured/reporting-page.vue
Labels: bug, VueJS

#1309 Update estimateCarriers view to allow multiple target countries
  _dev/.storybook/mock/product-feed.ts
  _dev/src/components/campaigns/campaign-card.vue
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/src/providers/shipping-rate-provider.spec.ts
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: VueJS

#1026 Allow several countries to be set in product feed (will sync products for multiple countries)
  _dev/src/components/commons/select-country.spec.ts
  _dev/src/components/commons/select-country.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
Labels: enhancement, VueJS

#1324 Changes from feedback of beta.10
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/base/_typography.scss
Labels: bug, VueJS

#1330 Changes from feedback of beta.11
  _dev/src/assets/scss/base/_border.scss
  _dev/src/assets/scss/layouts/_form.scss
Labels: enhancement, VueJS

#1327 Automatically dispatch claim verification meta if claimed or no not verified
  _dev/src/store/modules/accounts/actions.ts
Labels: enhancement, VueJS

#1322 Enable Multi target countries feature and update Shipping settings form
  _dev/.storybook/mock/product-feed.ts
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/components/_button.scss
  _dev/src/components/campaigns/campaign-card.vue
  _dev/src/components/commons/select-country.spec.ts
  _dev/src/components/commons/select-country.vue
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
  _dev/src/providers/shipping-rate-provider.spec.ts
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/providers/shipping-settings-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/LocalStorage.ts
  psxmarketingwithgoogle.php
Labels: Feature, waiting for PM, VueJS

#1306 Improvements UX on productFeed section
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/base/_typography.scss
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
Labels: enhancement, VueJS

#1334 Fix display of existing data from API and local storage
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
Labels: bug, VueJS

#1333 Add elements in debug page for testing migration sync
  _dev/src/store/modules/product-feed/actions-types.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/views/debug.vue
Labels: enhancement, VueJS
