Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-05, with the labels that each got.

#1012 Multiple target countries on settings of sync
  _dev/src/components/commons/select-country.vue
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
Labels: enhancement, VueJS

#1008 Phone verification improvements
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/layouts/_form.scss
  _dev/src/components/merchant-center-account/phone-verification/phone-verification-popin.vue
Labels: enhancement, VueJS

#1011 Refacto UI attribute mapping
  _dev/src/assets/images/compare-arrows.svg
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/layouts/_sizing.scss
  _dev/src/assets/scss/pages/_attribute-mapping.scss
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
Labels: enhancement, VueJS

#1015 Fix changing country in campaign creation
  _dev/src/components/commons/select-country.vue
Labels: bug, VueJS

#1016 Attribute EAN13 is now EAN
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: bug, VueJS

#1021 Require v1.17 of module to be installed
  _dev/.env
Labels: enhancement, VueJS

#1020 Make the attribute mapping values match the API
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/assets/json/translations/ru/ui.json
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/AttributeMapping.ts
Labels: bug, VueJS

#1025 FIX : props missing because of revert commit
  _dev/src/components/commons/select-country.vue
Labels: bug, VueJS

#1027 Fix : Regression on bêta for multiple country
  _dev/src/components/commons/select-country.vue
Labels: bug, VueJS

#1029 Improvement : delete product feed if cancel configuration
  _dev/src/components/product-feed/product-feed-popin-cancel.vue
Labels: enhancement, VueJS

#1024 In product feed summary, add an edit button for each unmapped attribute
  _dev/src/components/product-feed/commons/table-row-mapping.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.spec.ts
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/store/modules/product-feed/mutations.ts
Labels: enhancement, VueJS

#1033 Replace API call for retrieve mapping summary on productFeed
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters-types.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/views/onboarding-page.vue
Labels: VueJS

#1036 Fix button opening documentation
  _dev/src/components/help/faq.vue
Labels: bug, VueJS

#1038 Adding cast to get a string for country selected
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
Labels: bug, VueJS

#1037 Adding unit test for targetCountry components
  _dev/src/components/commons/select-country.spec.ts
  _dev/src/components/commons/select-country.vue
Labels: enhancement

#1039 Update wording when website verification fails
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
Labels: enhancement, VueJS

#1040 Require at least version 1.7.7 of CloudSync
  _dev/.env
Labels: enhancement, VueJS

#1046 Fix release reported on Sentry
  _dev/src/utils/Sentry.ts
Labels: bug, VueJS

#1044 Fix toast bad displaying
  _dev/src/views/product-feed-page.vue
  _dev/stories/product-feed-page.stories.ts
Labels: bug, VueJS

#1045 Keep the Google verification tag displayed after website is verified and claimed
  _dev/src/store/modules/accounts/actions.ts
Labels: enhancement, VueJS

#1043 Fix add hour in status in export feed tab
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed-page/sync-history/sync-history.vue
  _dev/stories/product-feed-page.stories.ts
Labels: enhancement, VueJS

#973 Integration product feed table status
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/layouts/_table.scss
  _dev/src/components/product-feed-page/product-feed-status-details.spec.ts
  _dev/src/components/product-feed-page/product-feed-table-status-details-row.vue
  _dev/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/src/components/product-feed-page/submitted-products/products-status-card.vue
  _dev/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/src/components/product-feed-page/sync-overview.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/views/product-feed-page.vue
  _dev/stories/product-feed-table-status-details.stories.ts
  _dev/tests/init.ts
Labels: enhancement, VueJS

#1050 Wrap text so it stays inside the button when too long
  _dev/src/components/commons/not-configured-card.vue
Labels: bug, VueJS
