Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-04, with the labels that each got.

#956 UXUI : shipping carriers updates
  _dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.vue
Labels: VueJS

#950 Attribute mapping values are now multilang
  classes/Repository/AttributesRepository.php
Labels: enhancement, PHP

#960 Empty states with different content and conditions
  _dev/src/App.vue
  _dev/src/assets/images/coaching.svg
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/not-configured-card.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
Labels: VueJS

#955 Tracking : add 3 new identify attributes
  _dev/src/main.ts
Labels: VueJS

#953 Reword new MCA funnel - requirements page
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/merchant-center-account/website-requirements/step-requirements.vue
  _dev/src/enums/merchant-center-account/website-requirements.ts
Labels: VueJS

#963 Fix : CSS + unsolicited toast display + remarketing tag popin after click on banner
  _dev/src/components/commons/banner-campaigns.vue
  _dev/src/components/commons/select-country.vue
  _dev/src/components/google-ads-account/google-ads-account-popin-new.vue
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/components/smart-shopping-campaigns/ssc-popin-activate-tracking.vue
  _dev/src/views/campaign-page.vue
  _dev/src/views/onboarding-page.vue
  _dev/src/views/product-feed-page.vue
Labels: bug, VueJS

#965 Resolve navigation problem on landing page
  _dev/src/router/index.ts
  _dev/src/views/landing-page.vue
Labels: bug, VueJS

#959 Add validator on targetCountry to avoid synchronization errors
  _dev/src/components/product-feed/settings/shipping-settings/shipping-settings.spec.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/utils/TargetCountryValidator.spec.ts
  _dev/src/utils/TargetCountryValidator.ts
Labels: bug, VueJS

#832 CI/CD - Improved workflows (cdn/storybook)
  .github/README.md
  .github/pics/storage-ci-cd.png
  .github/pics/storybook-ci-cd.png
  .github/workflows/cdn.yml
  .github/workflows/publish.yml
  .github/workflows/storybook-ci-cd.yml
Labels: waiting for author

#967 Decrease width of MCA requirements popin
  _dev/src/components/merchant-center-account/merchant-center-account-popin-website-requirements.vue
Labels: bug, VueJS

#968 Delete localstorage when disconnecting Google ou Merchant Center accounts
  _dev/src/components/google-account/google-account-popin-disconnect.vue
  _dev/src/components/merchant-center-account/merchant-center-account-popin-disconnect.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/utils/LocalStorage.ts
Labels: bug, VueJS

#970 Add new method for filter mapping without ID
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/utils/AttributeMapping.spec.ts
  _dev/src/utils/AttributeMapping.ts
Labels: VueJS

#972 CSS popin configured : title bigger
  _dev/src/components/commons/popin-configured.vue
Labels: bug, VueJS

#974 Fix : modal and popin display before billing done in google ads
  _dev/src/components/smart-shopping-campaigns/smart-shopping-campaign-card.vue
  _dev/src/views/onboarding-page.vue
Labels: bug, VueJS

#969 Display creation of Google Ads account in only one step
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/select-country.vue
  _dev/src/components/google-ads-account/google-ads-account-popin-new.spec.ts
  _dev/src/components/google-ads-account/google-ads-account-popin-new.vue
  _dev/stories/google-ads-account-popin-new.stories.ts
Labels: enhancement, VueJS

#971 Allow safe-mode uninstallation when PHP is not compliant
  psxmarketingwithgoogle.php
Labels: enhancement, PHP

#979 Fix typo in text
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#977 Add the multi lang attribute on attributeMapping
  _dev/.storybook/mock/product-feed.js
  _dev/src/assets/scss/layouts/_table.scss
  _dev/src/components/product-feed/commons/table-row-mapping.vue
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/attributes-to-map.json
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
  _dev/src/utils/AttributeMapping.spec.ts
  _dev/src/utils/AttributeMapping.ts
  classes/Repository/AttributesRepository.php
Labels: enhancement, VueJS

#978 Campaign performances table : replace button because no link available yet
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
Labels: bug, VueJS

#982 Open popin of complete configuration before remarketing tags checks
  _dev/src/components/commons/popin-configured.vue
  _dev/src/views/onboarding-page.vue
Labels: bug, VueJS

#981 Fix display of campaign page when module is not configured
  _dev/src/components/smart-shopping-campaigns/campaign-card.vue
Labels: bug, VueJS

#983 Add condition to avoid error on prescan page
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
Labels: bug, VueJS

#984 Fix translations on empty states
  _dev/src/assets/json/translations/en/ui.json
Labels: VueJS

#985 Remove condition to display banner campaign and fix test
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/components/smart-shopping-campaign/smart-shoppinh-campaign-table-list.spec.ts
Labels: bug, VueJS

#986 Disconnect ads account when merchand disconnect the gmc
  _dev/src/store/modules/accounts/actions.ts
Labels: bug, VueJS

#988 Fix typo on product feed tab
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#990 Fix : empty states were not displayed on disconnect google ads
  _dev/src/components/commons/banner-campaigns.vue
  _dev/src/components/commons/not-configured-card.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/components/smart-shopping-campaign/smart-shoppinh-campaign-table-list.spec.ts
Labels: bug, VueJS

#991 Missing letter in english translation
  _dev/src/assets/json/translations/en/ui.json
Labels: bug, VueJS

#997 Update eventbus version
  _dev/.env
Labels: enhancement, VueJS

#1000 Fix an issue preventing the front office to be displayed in some cases when the module is enabled + Other improvements of conversion actions
  classes/Buffer/TemplateBuffer.php
  classes/Handler/RemarketingHookHandler.php
  classes/Provider/CartEventDataProvider.php
  classes/Provider/ProductDataProvider.php
Labels: bug, PHP

#1001 Add common data on conversion action about purchase to avoid conversion value = 1
  classes/DTO/Remarketing/PurchaseEventData.php
  classes/Provider/PurchaseEventDataProvider.php
Labels: bug, PHP

#999 Modify the UI for attribute mapping summary
  _dev/src/assets/images/compare-arrows.svg
  _dev/src/assets/images/table-chart.svg
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/base/_color.scss
  _dev/src/assets/scss/layouts/_table.scss
  _dev/src/components/product-feed/commons/table-row-mapping.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
Labels: enhancement, VueJS

#1003 Modify tooltip display and wording
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/store/modules/product-feed/attributes-to-map.json
Labels: enhancement, VueJS

#1006 Fix some issues on product feed while testing beta.1
  _dev/src/components/product-feed/product-feed-card.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
Labels: bug, VueJS

#1009 Add hour to next sync date
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed-page/sync-history/sync-history.vue
Labels: enhancement, VueJS
