Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-07, with the labels that each got.

#1084 Show only countries in dropdown if they exist in shipping carriers
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/commons/select-country.vue
  _dev/src/components/product-feed/settings/shipping-settings/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/shipping-settings/shipping-settings.vue
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
  _dev/src/providers/shipping-settings-provider.spec.ts
  _dev/src/providers/shipping-settings-provider.ts
  _dev/stories/product-feed-settings.stories.ts
Labels: enhancement, VueJS

#1150 Fix the target country filtering on the product feed section
  _dev/.storybook/mock/product-feed.js
  _dev/src/components/commons/select-country.vue
  _dev/src/components/google-ads-account/google-ads-account-popin-new.vue
  _dev/src/components/product-feed/settings/target-countries/target-countries.vue
  _dev/src/store/modules/app/getters.ts
  _dev/src/store/modules/app/state.ts
  _dev/src/utils/TargetCountryValidator.spec.ts
  _dev/src/utils/TargetCountryValidator.ts
Labels: VueJS

#1152 Add check about ajax requests
  classes/Handler/RemarketingHookHandler.php
Labels: bug, PHP

#1154 Use images use stored online instead of on the shop
  .github/workflows/cdn.yml
  _dev/vue.config.js
Labels: enhancement, VueJS

#1153 Fix display of currency on campaign list + fix language context when formating a price
  _dev/.storybook/preview.js
  _dev/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-popin-recap.vue
  _dev/src/components/campaign/campaign-table-list-row.vue
  _dev/src/shims-tsx.d.ts
  _dev/src/store/modules/campaigns/actions.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/utils/Filters.ts
Labels: enhancement, VueJS

#1155 Forbid setting campaigns end date before today
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/src/components/campaign-creation/campaign-creation.vue
  _dev/tests/init.ts
Labels: enhancement, VueJS

#1162 Add missing border on button
  _dev/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-filter-confirm-cancel.vue
Labels: VueJS

#1168 Change vertical order of modal
  _dev/src/assets/scss/base/_common.scss
  _dev/src/assets/scss/components/_helper-shopid.scss
Labels: enhancement, VueJS

#1166 Request refresh of campaign lists after form submission
  _dev/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-popin-recap.vue
Labels: bug, VueJS

#1165 Change modale for Pmax migration
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/pmax/pmax-integration-modals/pmax-discover-modal.vue
  _dev/src/views/onboarding-page.vue
Labels: VueJS

#1167 Change wording for PMax banner
  _dev/src/assets/json/translations/en/ui.json
Labels: VueJS

#1172 Change illustrations on landing page
  _dev/src/assets/images/Google-Commercial-img.png
  _dev/src/assets/images/Google-Shopping-Tab-img.png
  _dev/src/assets/images/Merchant-Center-img.png
  _dev/src/assets/images/prestashop-google-img.png
Labels: VueJS

#1173 Display feedback when campaign's end date is invalid
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/campaign-creation/campaign-creation.vue
Labels: enhancement, VueJS

#1176 Add missing PMax pictures (NL & PT)
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-EN.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-ES.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-FR.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-IT.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-NL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-PL.png
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-PT.png
Labels: enhancement, VueJS

#1178 Update translations for "I understand"
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
Labels: enhancement, VueJS

#1177 Add missing PMax picture in DE
  _dev/src/assets/images/pmax-modal/pmax-modal-ssc-deprecated-DE.png
Labels: enhancement, VueJS
