Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-12, with the labels that each got.

#1335 Fix loading of data coming from API
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
Labels: bug, VueJS

#1336 Update stories about Delivery rates
  _dev/.storybook/mock/product-feed.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/stories/product-feed-settings.stories.ts
Labels: enhancement, VueJS

#1340 Improve multi target countries from feedback of beta.7
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
  _dev/src/components/product-feed/summary/product-feed-summary-cards.vue
Labels: bug, VueJS

#1342 Fix feedback UI for productFeed
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
Labels: enhancement, VueJS

#1344 Improve multi target countries from feedback of beta.8
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/shipping-setup/shipping-setup.vue
  _dev/src/providers/shipping-rate-provider.ts
  _dev/src/store/modules/product-feed/actions.spec.ts
  _dev/src/store/modules/product-feed/actions.ts
Labels: bug, enhancement

#1337 Display warning when a potentially mandatory attribute has no value
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.spec.ts
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
Labels: bug, VueJS

#1351 Resolve issue from review of estimate carrier UX
  _dev/src/assets/scss/abstracts/_variables.scss
  _dev/src/assets/scss/base/_common.scss
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
Labels: VueJS

#1356 Hotfix: Fix reload of existing product feed when carriers have been imported, never estimated
  _dev/src/store/modules/product-feed/actions.ts
  psxmarketingwithgoogle.php
Labels: bug, VueJS

#1353 Reset carrier forms on country updates
  _dev/.storybook/mock/product-feed.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/delivery-time-and-rates.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-rate.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.spec.ts
  _dev/src/components/product-feed/settings/delivery-time-and-rates/target-countries.vue
  _dev/src/enums/product-feed/attribute-mapping-categories.ts
  _dev/src/providers/shipping-settings-provider.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/product-feed/state.ts
Labels: enhancement, VueJS
