Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2022-01, with the labels that each got.

#821 Updates chromatic GA workflow with setup-node@v2
  .github/workflows/chromatic.yml
  _dev/src/App.vue
Labels: waiting for UX

#818 Improve campaign page with skeleton
  _dev/src/views/campaign-page.vue
Labels: bug, VueJS

#826 Put CDN URL on allowUrls for only trigger module errors
  _dev/src/utils/Sentry.ts
Labels: enhancement, VueJS

#782 Refacto filter component for SSC
  _dev/.storybook/mock/smart-shopping-campaigns.js
  _dev/package-lock.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/components/_filters.scss
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-confirm-cancel.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-dimension.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-filter.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/lib/i18n.ts
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/getters.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations-types.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
  _dev/src/utils/SSCFilters.spec.ts
  _dev/src/utils/SSCFilters.ts
  _dev/stories/smart-shopping-campaign-creation-filter-popin.stories.ts
  _dev/stories/smart-shopping-campaign-creation-popin-recap.stories.ts
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: Feature, VueJS

#827 Bump to v1.12.x
  psxmarketingwithgoogle.php
Labels: PHP

#831 Retry introducing typescript in one Vue component
  _dev/src/components/product-feed/settings/shipping-settings/table-row-carrier.vue
Labels: enhancement, VueJS

#829 Edit campaign filters
  _dev/.storybook/mock/smart-shopping-campaigns.js
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/scss/base/_color.scss
  _dev/src/assets/scss/components/_filters.scss
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-dimension.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-filter.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.spec.ts
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/state.ts
  _dev/src/utils/CompareYears.ts
  _dev/src/utils/SSCFilters.ts
  _dev/src/views/campaign-page.vue
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: Feature, VueJS

#833 Update eslint to v0.2.x
  _dev/package-lock.json
  _dev/package.json
  _dev/src/components/chart/chart.vue
  _dev/src/components/commons/alert-update-module.vue
  _dev/src/components/commons/select-country.vue
  _dev/src/components/google-account/google-account-card.vue
  _dev/src/components/google-ads-account/google-ads-account-card.vue
  _dev/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/src/components/merchant-center-account/website-requirements/step-store-info.vue
  _dev/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/src/components/product-feed/product-feed-settings-export-exclude-brand.vue
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.vue
  _dev/src/components/smart-shopping-campaign/reporting/key-metrics/key-metrics-chart-wrapper.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list.vue
  _dev/src/store/modules/accounts/actions.ts
  _dev/src/store/modules/app/actions.ts
  _dev/src/store/modules/free-listing/actions.ts
  _dev/src/store/modules/google-ads/actions.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/store/modules/smart-shopping-campaigns/actions.ts
  _dev/src/store/modules/smart-shopping-campaigns/mutations.ts
  _dev/src/utils/CompareYears.ts
  _dev/src/utils/Filters.ts
  _dev/src/utils/SSCFilters.ts
  _dev/src/views/configuration.vue
  _dev/tests/store.ts
  _dev/vue.config.js
Labels: enhancement, VueJS

#834 Add missing test for select filters button that should be disabled
  _dev/.storybook/mock/smart-shopping-campaigns.js
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation.spec.ts
Labels: enhancement, VueJS

#838 Fix build of storybook with Typescript in components
  _dev/.storybook/webpack.config.js
Labels: bug, VueJS

#824 Test/ga chromatic
  .github/workflows/chromatic.yml
Labels: enhancement

#837 Translate filter name if product condition
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-filter-item.vue
Labels: VueJS

#839 Fix chromatic feedback on unhandled filter story
  _dev/.storybook/mock/smart-shopping-campaigns.js
  _dev/stories/smart-shopping-campaign-creation.stories.ts
Labels: bug, VueJS

#841 Fix storybook dates display + edition filters
  _dev/.storybook/mock/campaigns-list.js
  _dev/src/components/smart-shopping-campaign-creation/smart-shopping-campaign-creation-filter-popin/smart-shopping-campaign-creation-popin-recap.vue
  _dev/src/components/smart-shopping-campaign/smart-shopping-campaign-table-list-row.vue
  _dev/stories/smart-shopping-campaign-creation.stories.ts
  _dev/stories/smart-shopping-campaign-table-list.stories.ts
Labels: bug, VueJS
