Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-05, with the labels that each got.

#1452 Display info icon in light grey
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-popin-website-requirements.vue
  _dev/apps/ui/src/components/product-feed/settings/commons/settings-footer.vue
Labels: bug, VueJS

#1453 Improve some parts of the application after the rebranding has been applied
  _dev/apps/ui/.storybook/mock/campaigns-list.ts
  _dev/apps/ui/src/assets/scss/abstracts/_functions.scss
  _dev/apps/ui/src/assets/scss/components/_sync-history.scss
  _dev/apps/ui/src/assets/scss/layouts/_table.scss
  _dev/apps/ui/src/components/help/faq.vue
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1454 Update background colors of alerts
  _dev/apps/ui/src/assets/scss/abstracts/_variables.scss
  _dev/apps/ui/src/assets/scss/base/_common.scss
  _dev/apps/ui/src/assets/scss/components/_product-category-checkbox.scss
  _dev/apps/ui/src/assets/scss/components/_shipping_setup.scss
  _dev/apps/ui/src/assets/scss/layouts/_form.scss
  _dev/apps/ui/src/assets/scss/layouts/_table.scss
  _dev/apps/ui/stories/base-alerts.stories.ts
Labels: enhancement, VueJS

#1448 feat(ui): hide create account if merchant already created GMC account from module
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/src/store/modules/accounts/state.ts
  _dev/apps/ui/stories/merchant-center-account-card.stories.ts
Labels: enhancement, VueJS

#1462 Bring back translations about sync summary
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: bug, VueJS

#1456 Display account suspension alert on new product feed page
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-links.ts
  _dev/apps/ui/src/components/product-feed-page/sync-overview.vue
  _dev/apps/ui/src/store/modules/accounts/state.ts
  _dev/apps/ui/stories/product-feed-page.stories.ts
Labels: Feature, VueJS

#1466 Make default value of sync context null
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/sync-overview.vue
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
Labels: bug, VueJS

#1469 Integrate status cards on verification & sync steps
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/assets/scss/components/_productfeedreportcard.scss
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-links.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-history/sync-history.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-history/sync-state.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-product-status-card.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-sync-status-card.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.spec.ts
  _dev/apps/ui/src/components/product-feed-page/submitted-products/products-status-card.vue
  _dev/apps/ui/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/apps/ui/src/shims-tsx.d.ts
  _dev/apps/ui/src/store/modules/app/getters-types.ts
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/store/modules/app/index.ts
  _dev/apps/ui/src/store/modules/app/state.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/src/views/product-feed-page.vue
  _dev/apps/ui/stories/product-feed-overview.stories.ts
  _dev/apps/ui/stories/product-feed-page-components-configuration.stories.ts
  _dev/apps/ui/stories/product-feed-page-components-submitted-products.stories.ts
  _dev/apps/ui/stories/product-feed-page-components-verified-products.stories.ts
  _dev/apps/ui/stories/product-feed-page.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
Labels: Feature, VueJS

#1478 Add links in product feed configuration used panel
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/shims-tsx.d.ts
  _dev/apps/ui/src/store/modules/app/getters-types.ts
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/store/modules/app/index.ts
  _dev/apps/ui/src/store/modules/app/state.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
Labels: enhancement, VueJS

#1479 Plug verification stats to API (existing and new routes)
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters-types.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations-types.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/stories/product-feed-page-components-verified-products.stories.ts
  _dev/apps/ui/stories/product-feed-page.stories.ts
Labels: enhancement, VueJS

#1481 Improvements from beta.2
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/lib/i18n.ts
  _dev/apps/ui/src/store/modules/app/index.ts
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations-types.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/src/utils/Dates.ts
  _dev/apps/ui/stories/product-feed-page.stories.ts
Labels: enhancement, VueJS
