Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-01, with the labels that each got.

#1359 Refacto API calls to shop + Detect when a user is logged out from its BO
  _dev/src/App.vue
  _dev/src/api/HttpClientError.ts
  _dev/src/api/shopClient.ts
  _dev/src/store/modules/accounts/actions.ts
  _dev/src/store/modules/app/actions.ts
  _dev/src/store/modules/campaigns/actions.ts
  _dev/src/store/modules/free-listing/actions.ts
  _dev/src/store/modules/google-ads/actions.ts
  _dev/src/store/modules/product-feed/actions.ts
Labels: enhancement, VueJS

#1361 Update style of badges in reports tab
  _dev/src/components/campaign/reporting/campaigns-performance/campaigns-performance-table-row.vue
Labels: bug, VueJS

#1363 Fix focus style of secondary outlined buttons
  _dev/src/assets/scss/components/_button.scss
Labels: bug, VueJS

#1362 Display a specific message when the campaign name is too long
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/src/components/campaign-creation/campaign-creation.vue
Labels: enhancement, VueJS

#1360 Modify spacement on estimate carrier step
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/src/store/modules/product-feed/actions.ts
Labels: VueJS

#1367 Fix spacement on custom carrier card
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
Labels: VueJS

#1371 Add prefix URL to sourcemaps sent to Sentry so they can be used on stacktraces
  .github/workflows/publish.yml
Labels: enhancement, VueJS

#1370 Avoid issues related to CORS policy on popup
  _dev/src/components/commons/glass.vue
  _dev/src/components/google-account/google-account-card.vue
Labels: bug, VueJS

#1369 Fix dynamic display of attributes list to map
  _dev/.storybook/preview.js
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.spec.ts
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/store/modules/product-feed/actions.ts
  _dev/stories/product-feed-settings.stories.ts
Labels: bug, VueJS

#1368 Catch errors happening during the whole verification process, even on the retrieval of status
  _dev/src/store/modules/accounts/actions.ts
Labels: bug, VueJS

#1372 Enable Replays on Sentry
  _dev/package-lock.json
  _dev/package.json
  _dev/src/utils/Sentry.ts
Labels: enhancement, VueJS

#1366 Introduce CloudSync consent screen
  _dev/src/views/onboarding-page.vue
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
  views/templates/admin/app.tpl
Labels: Feature, PHP, VueJS

#1374 Load CSC from CloudSync module when installed version is at least 1.9.0
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
Labels: bug, VueJS

#1375 Reinit CSC when the user comes back on config tab
  _dev/.storybook/mock/ps-event-bus.ts
  _dev/.storybook/preview-head.html
  _dev/src/shims-tsx.d.ts
  _dev/src/views/onboarding-page.vue
  _dev/stories/onboarding-page.stories.ts
Labels: bug, VueJS

#1373 Fix management of stored data for attributes mapping
  _dev/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/src/components/product-feed/settings/summary/summary.vue
  _dev/src/store/modules/product-feed/actions-types.ts
  _dev/src/store/modules/product-feed/actions.spec.ts
  _dev/src/store/modules/product-feed/actions.ts
  _dev/src/store/modules/product-feed/getters.ts
  _dev/src/store/modules/product-feed/mutations-types.ts
  _dev/src/store/modules/product-feed/mutations.ts
  _dev/src/utils/AttributeMapping.spec.ts
  _dev/src/utils/AttributeMapping.ts
  _dev/src/utils/LocalStorage.ts
Labels: bug, VueJS

#1376 Do not disturb the onboarding process when module is not up to date yet
  _dev/src/views/onboarding-page.vue
  psxmarketingwithgoogle.php
Labels: bug, VueJS

#1377 Add new message when targetCountries and shop language not matched
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/stories/product-feed-pre-scan-table-status.stories.ts
Labels: enhancement, VueJS

#1379 Upgrade dependency vlucas/phpdotenv
  composer.json
  composer.lock
Labels: enhancement, PHP
