Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-06, with the labels that each got.

#1486 Rename data about synced products
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/stories/product-feed-page-components-submitted-products.stories.ts
  _dev/apps/ui/stories/product-feed-page.stories.ts
  _dev/apps/ui/stories/smart-shopping-campaign-creation.stories.ts
Labels: enhancement, VueJS

#1484 Update style from design check
  _dev/apps/ui/src/assets/scss/components/_badge.scss
  _dev/apps/ui/src/assets/scss/components/_sync-history.scss
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
Labels: enhancement, VueJS

#1485 Plug verification stats cards to new route of API
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations-types.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/stories/product-feed-page-components-verified-products.stories.ts
Labels: enhancement, VueJS

#1487 Fix loading of currencies on latest versions of PS
  classes/Repository/CurrencyRepository.php
Labels: bug, PHP

#1490 Update wording of cards
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1494 Fix display of button even when behind a wall
  _dev/apps/ui/src/assets/scss/components/_onboardingcard.scss
Labels: bug, VueJS

#1498 Upgrade TypeScript to 4.9.5
  _dev/apps/ui/package.json
  _dev/pnpm-lock.yaml
Labels: enhancement, dependencies, VueJS

#1499 Improve header of product status details in product feed
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue
Labels: bug, VueJS

#1497 Introduce non-compliant products page
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/assets/scss/base/_typography.scss
  _dev/apps/ui/src/assets/scss/layouts/_form.scss
  _dev/apps/ui/src/assets/scss/layouts/_table.scss
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-page.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters-types.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations-types.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/src/views/product-feed-page.vue
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-configuration.stories.ts
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-submitted-products.stories.ts
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-verified-products.stories.ts
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page.stories.ts
  _dev/apps/ui/stories/product-feed-page/non-compliant-products-page/non-compliant-products-page.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1502 Allow singular form of 'View products'
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-page.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1500 Introduce non-compliant product page details
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-page.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-row.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/getters-types.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.spec.ts
  _dev/apps/ui/src/store/modules/product-feed/getters.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations-types.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.spec.ts
  _dev/apps/ui/src/store/modules/product-feed/mutations.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/src/views/product-feed-page.vue
  _dev/apps/ui/stories/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-page.stories.ts
  _dev/apps/ui/stories/product-feed-pre-scan-table-status.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1480 Display currencies in product feed's configuration
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
Labels: enhancement, VueJS

#1504 Fix source of currencies list + add events about product feed status
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-row.vue
Labels: bug, enhancement, VueJS

#1505 Make non-compliant card clickable even with value zero
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
Labels: bug, VueJS

#1508 Add wording about missing identifier
  _dev/apps/ui/src/assets/scss/layouts/_table.scss
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1513 Display errors about ineligible langs or currencies
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-configuration.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1517 Prevent rebranding on PrestaShop Edition to alter our interface
  _dev/apps/ui/src/main.ts
Labels: bug, VueJS

#1518 Fix color of alert when an unrelated currency is sent by the API
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.spec.ts
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page-components-configuration.stories.ts
Labels: bug, VueJS

#1515 Update wording on GMC card introduction
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1512 Add a button in the debug tab to force the creation of GMC accounts
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/src/views/debug.vue
Labels: Feature, VueJS

#1514 Fix status of campaign during edition
  _dev/apps/ui/src/components/campaign-creation/campaign-creation-filter-popin/campaign-creation-popin-recap.vue
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
Labels: bug, VueJS

#1521 feat: force hook when merchant connect GMC account
  _dev/apps/ui/src/store/modules/accounts/actions.ts
Labels: VueJS
