Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-07, with the labels that each got.

#1524 Add information on url to be redirect on the right module and domain
  _dev/apps/ui/src/components/help/faq.vue
Labels: VueJS

#1523 Remove SSC occurrences
  _dev/apps/ui/.storybook/mock/campaigns-list.ts
  _dev/apps/ui/.storybook/mock/campaigns.ts
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/campaign/campaign-table-list.spec.ts
  _dev/apps/ui/src/components/campaign/campaign-table-list.vue
  _dev/apps/ui/src/router/index.ts
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
  _dev/apps/ui/src/store/modules/campaigns/getters.ts
  _dev/apps/ui/src/store/modules/campaigns/mutations.ts
  _dev/apps/ui/src/store/modules/campaigns/state.ts
  _dev/apps/ui/src/views/onboarding-page.vue
  _dev/apps/ui/stories/banners-ads-overviews.stories.ts
  _dev/apps/ui/stories/smart-shopping-campaign-creation.stories.ts
  _dev/apps/ui/stories/smart-shopping-campaign-table-list.stories.ts
Labels: VueJS

#1526 fix: resolve error on storybook build
  _dev/apps/ui/src/components/help/faq.vue
  _dev/apps/ui/stories/help-page.stories.ts
Labels: VueJS

#1528 Fix build of storybook on chromatic
  _dev/apps/ui/.storybook/mock/reporting/daily-results.ts
  _dev/apps/ui/.storybook/mock/reporting/kpi.ts
  _dev/apps/ui/.storybook/mock/reporting/next-page-token.js
  _dev/apps/ui/.storybook/mock/reporting/next-page-token.ts
  _dev/apps/ui/.storybook/mock/reporting/products-partitions-performance.ts
  _dev/apps/ui/.storybook/mock/reporting/products-performance.ts
  _dev/apps/ui/.storybook/utils/date-generator.ts
  _dev/apps/ui/stories/campaigns-performance-table.stories.ts
  _dev/apps/ui/stories/filters-performance-table.stories.ts
  _dev/apps/ui/stories/key-metrics.stories.ts
  _dev/apps/ui/stories/products-performance-table.stories.ts
  _dev/apps/ui/stories/reporting-daily-results-chart.stories.ts
Labels: bug, waiting for UX

#1531 Upgrade alert with features
  _dev/apps/ui/.eslintrc.js
  _dev/apps/ui/.storybook/main.ts
  _dev/apps/ui/package.json
  _dev/apps/ui/src/App.vue
  _dev/apps/ui/src/components/commons/alert-update-module.stories.ts
  _dev/apps/ui/src/components/commons/alert-update-module.vue
  _dev/packages/mktg-with-google-common/translations/en/ui.json
  _dev/pnpm-lock.yaml
Labels: Feature, VueJS

#1529 Follow events happening during reverification and claiming process
  _dev/apps/verification-tag/package.json
  _dev/apps/verification-tag/src/index.ts
  _dev/apps/verification-tag/src/verification-tag-retriever.ts
  _dev/apps/verification-tag/webpack.config.js
  _dev/pnpm-lock.yaml
  psxmarketingwithgoogle.php
Labels: enhancement, VueJS

#1533 Bring back language selector on Storybook
  _dev/apps/ui/.storybook/main.ts
  _dev/apps/ui/.storybook/preview.js
  _dev/apps/ui/package.json
  _dev/pnpm-lock.yaml
Labels: Feature, VueJS

#1535 Lazy load translations for performance
  _dev/apps/ui/.storybook/preview.js
  _dev/apps/ui/src/lib/i18n.ts
  _dev/apps/ui/src/lib/translations.ts
  _dev/apps/ui/tests/init.ts
Labels: enhancement, VueJS

#1538 Fix backward compatibility
  _dev/apps/ui/src/bc-ante-vite.ts
Labels: bug, VueJS

#1543 Use v5 of PS Accounts components
  views/templates/admin/app.tpl
Labels: enhancement, VueJS

#1545 Always display CloudSync consent screen, even if PS Accounts is not onboarded
  _dev/apps/ui/src/views/onboarding-page.vue
Labels: enhancement, VueJS

#1544 Update landing page
  _dev/apps/ui/src/assets/images/120x120_MARKETING_BACK-OFFICE_01.png
  _dev/apps/ui/src/assets/images/120x120_MARKETING_BACK-OFFICE_02.png
  _dev/apps/ui/src/assets/images/120x120_MARKETING_BACK-OFFICE_03.png
  _dev/apps/ui/src/assets/images/Google-Shopping-Tab-img.png
  _dev/apps/ui/src/assets/images/Merchant-Center-img.png
  _dev/apps/ui/src/assets/images/banner/PS_MARKETING_VOUCHER_DOLLAR.png
  _dev/apps/ui/src/assets/images/banner/PS_MARKETING_VOUCHER_EURO.png
  _dev/apps/ui/src/assets/images/banner/PS_MARKETING_VOUCHER_ZLOTY.png
  _dev/apps/ui/src/assets/images/banner/ads-dollars.svg
  _dev/apps/ui/src/assets/images/banner/ads-euro.svg
  _dev/apps/ui/src/assets/images/banner/ads-pounds.svg
  _dev/apps/ui/src/assets/images/banner/ads-zloty.svg
  _dev/apps/ui/src/assets/scss/components/_landingpagecontent.scss
  _dev/apps/ui/src/assets/scss/components/_landingpageheader.scss
  _dev/apps/ui/src/assets/scss/pages/_landingpage.scss
  _dev/apps/ui/src/components/landing-page/landing-page-content.vue
  _dev/apps/ui/src/components/landing-page/landing-page-header.vue
  _dev/apps/ui/src/store/modules/free-listing/state.ts
  _dev/apps/ui/src/utils/ImageFromCurrency.spec.ts
  _dev/apps/ui/src/utils/ImageFromCurrency.ts
  _dev/apps/ui/src/views/landing-page.vue
  _dev/apps/ui/stories/landing-page-content.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
  views/img/Google-Ads-icon-grey.svg
  views/img/Google-Ads-icon.svg
  views/img/Google-Ads-img.png
  views/img/Google-Commercial-icon-grey.svg
  views/img/Google-Shopping-Tab-img.png
  views/img/Merchant-Center-img.png
  views/img/PS_MARKETING_VOUCHER_DOLLAR.png
  views/img/PS_MARKETING_VOUCHER_EURO.png
  views/img/PS_MARKETING_VOUCHER_ZLOTY.png
  views/img/ads-dollars.svg
  views/img/ads-euro.svg
  views/img/ads-marketing.svg
  views/img/ads-poland.svg
  views/img/ads-pounds.svg
  views/img/boost-campaing.svg
  views/img/campaign-24px.svg
  views/img/google-merchant-center-icon-grey.svg
  views/img/google-shopping-icon-grey.svg
  views/img/google-shopping-icon.svg
  views/img/local-offer.svg
  views/img/prestashop-google-img.png
  views/img/prestashop-google-logo.png
  views/img/prestashop-google-logo.svg
  views/img/prestashop-google-visual.png
  views/img/product-feed-icon-grey.svg
  views/img/product-feed-icon.svg
  views/img/puffin-logo.svg
  views/img/temp_target.svg
  views/img/tips-and-tricks-christophe.png
Labels: enhancement, VueJS
