Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-03, with the labels that each got.

#1384 Retrieve website verification tag from BO dashboard when obsolete
  _dev/.eslintrc.js
  _dev/apps/ui/.eslintrc.js
  _dev/apps/ui/.storybook/preview.js
  _dev/apps/ui/package.json
  _dev/apps/ui/src/App.vue
  _dev/apps/ui/src/components/google-ads-account/google-ads-account-card.vue
  _dev/apps/ui/src/components/merchant-center-account/website-requirements/step-store-info.vue
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/app/actions.ts
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
  _dev/apps/ui/src/store/modules/free-listing/actions.ts
  _dev/apps/ui/src/store/modules/google-ads/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/utils/Sentry.ts
  _dev/apps/ui/src/views/onboarding-page.vue
  _dev/apps/verification-tag/package.json
  _dev/apps/verification-tag/src/index.ts
  _dev/apps/verification-tag/tsconfig.json
  _dev/apps/verification-tag/webpack.config.js
  _dev/packages/mktg-with-google-common/api/HttpClientError.ts
  _dev/packages/mktg-with-google-common/api/onboardingClient.ts
  _dev/packages/mktg-with-google-common/api/shopClient.ts
  _dev/packages/mktg-with-google-common/index.ts
  _dev/packages/mktg-with-google-common/package.json
  _dev/pnpm-lock.yaml
  classes/Provider/VerificationTagDataProvider.php
  classes/Repository/VerificationTagRepository.php
  config/common/provider.yml
  config/common/repository.yml
  controllers/admin/AdminAjaxPsxMktgWithGoogleController.php
  psxmarketingwithgoogle.php
  tests/unit/Builder/CarrierBuilderTest.php
  tests/unit/Provider/VerificationTagDataProviderTest.php
Labels: Feature, PHP, VueJS

#1404 Change constructor call
  _dev/packages/mktg-with-google-common/api/HttpClientError.ts
Labels: bug

#1407 Improve verification tag renewal process from feedback
  _dev/apps/verification-tag/src/index.ts
  _dev/apps/verification-tag/src/verification-tag-retriever.spec.ts
  _dev/apps/verification-tag/src/verification-tag-retriever.ts
  psxmarketingwithgoogle.php
Labels: enhancement, VueJS

#1408 Resolve problem when retrieving products filters
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
Labels: enhancement

#1409 Avoid calls to json() when possible
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
  _dev/apps/ui/src/store/modules/free-listing/actions.ts
  _dev/apps/ui/src/store/modules/google-ads/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/tsconfig.json
  _dev/apps/verification-tag/src/verification-tag-retriever.spec.ts
  _dev/apps/verification-tag/src/verification-tag-retriever.ts
  _dev/packages/mktg-with-google-common/api/onboardingClient.ts
Labels: bug, VueJS

#1410 Remove remaining code from era where multistore was not possible on the module
  _dev/apps/ui/src/store/modules/accounts/actions-types.ts
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/views/onboarding-page.vue
Labels: enhancement, VueJS

#1413 Remove duplicate .json call
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
Labels: bug

#1411 Display disapproved products even without issues linked to them
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/src/assets/json/googleUrl.json
  _dev/apps/ui/src/assets/json/translations/en/ui.json
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.spec.ts
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/stories/product-feed-table-status-details.stories.ts
Labels: enhancement, VueJS

#1416 Add modal when merchant was disconnected to PrestaShop BO
  _dev/apps/ui/src/App.vue
  _dev/apps/ui/src/assets/json/translations/en/ui.json
  _dev/apps/ui/src/assets/scss/base/_common.scss
  _dev/apps/ui/src/components/commons/user-not-connected-to-bo-popin.vue
  _dev/apps/ui/src/store/modules/app/mutations-types.ts
  _dev/apps/ui/src/store/modules/app/mutations.ts
  _dev/apps/ui/src/store/modules/app/state.ts
  _dev/apps/ui/stories/user-not-connected-to-bo.stories.ts
Labels: Feature

#1419 Fix paths to template paths
  classes/Handler/RemarketingHookHandler.php
Labels: bug, PHP

#1420 Bump accounts components
  _dev/apps/ui/package.json
  _dev/pnpm-lock.yaml
Labels: enhancement, VueJS

#1421 Use latest version of PHPStan
  .github/workflows/php.yml
  classes/Database/Uninstaller.php
  classes/Provider/CarrierDataProvider.php
  classes/Repository/CarrierRepository.php
  classes/Repository/ModuleRepository.php
  classes/Repository/StateRepository.php
  composer.json
  composer.lock
  config/admin/installer.yml
  config/admin/provider.yml
  config/common/repository.yml
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
  psxmarketingwithgoogle.php
Labels: enhancement, PHP

#1423 Reset campaigns lists when Google Ads is disconnected
  _dev/apps/ui/src/store/modules/google-ads/actions.ts
Labels: bug, VueJS

#1424 Open remarketing tag popin when after closing the config success popin
  _dev/apps/ui/src/components/campaigns/campaign-card.vue
  _dev/apps/ui/src/components/commons/popin-configured.vue
  _dev/apps/ui/src/views/onboarding-page.vue
Labels: bug, VueJS

#1425 Fix alignment of data in product feed table when all destination do not have the same status
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue
  _dev/apps/ui/stories/product-feed-table-status-details.stories.ts
Labels: bug, VueJS
