Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2023-02, with the labels that each got.

#1385 Fix chromatic workflow
  .github/workflows/chromatic.yml
Labels: bug, waiting for UX

#1381 Add message in productFeedPage summary for prescan error lang
  _dev/apps/ui/src/components/product-feed-page/product-feed-pre-scan-table-status-details.vue
  _dev/apps/ui/src/components/product-feed-page/submitted-products/submitted-products.vue
  _dev/apps/ui/stories/product-feed-page.stories.ts
  _dev/apps/ui/stories/product-feed-pre-scan-table-status.stories.ts
Labels: VueJS

#1388 Display currency of Google Ads account instead of shop's
  _dev/apps/ui/package.json
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/utils/Filters.ts
  _dev/apps/ui/src/utils/Price.ts
  _dev/apps/ui/tests/init.ts
  _dev/pnpm-lock.yaml
Labels: enhancement, VueJS

#1389 Introduce minimum recommended budget
  _dev/apps/ui/.env
  _dev/apps/ui/package.json
  _dev/apps/ui/src/assets/images/tips-and-tricks-christophe.png
  _dev/apps/ui/src/assets/json/translations/en/ui.json
  _dev/apps/ui/src/assets/scss/app.scss
  _dev/apps/ui/src/assets/scss/components/_tips-and-tricks.scss
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.spec.ts
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/commons/tips-and-tricks-card.spec.ts
  _dev/apps/ui/src/components/commons/tips-and-tricks-card.vue
  _dev/apps/ui/src/main.ts
  _dev/apps/ui/src/store/modules/campaigns/actions-types.ts
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
  _dev/apps/ui/src/utils/CampaignsBudget.ts
  _dev/apps/ui/stories/smart-shopping-campaign-creation.stories.ts
  _dev/apps/ui/stories/tips-and-tricks.stories.ts
  _dev/pnpm-lock.yaml
Labels: Feature, VueJS

#1390 Add missing input event
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
Labels: bug, VueJS

#1391 Add missing file for install
  .gitignore
  config.xml
Labels: bug

#1392 Use recommended budget in placeholder on creation campaign
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
Labels: VueJS

#1393 Change event for campaign budget
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
Labels: VueJS

#1394 Change wording for MPN section
  _dev/apps/ui/src/assets/json/translations/en/ui.json
Labels: VueJS

#1402 Add TypeScript on campaign performance mock
  _dev/apps/ui/.storybook/mock/reporting/campaigns-performance.ts
  _dev/apps/ui/src/store/modules/campaigns/getters.ts
  _dev/apps/ui/src/store/modules/campaigns/mutations.ts
  _dev/apps/ui/src/store/modules/campaigns/state.ts
  _dev/apps/ui/stories/campaigns-performance-table.stories.ts
  _dev/apps/ui/stories/key-metrics.stories.ts
Labels: enhancement, VueJS
