Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2024-03, with the labels that each got.

#1685 Update calculation of nav bar position
  _dev/apps/ui/src/App.vue
Labels: bug, VueJS

#1686 Add space below languages & currencies labels
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-row.vue
Labels: bug, VueJS

#1684 Hide Enhanced Conversion feature behind feature flag
  _dev/apps/ui/src/components/enhanced-conversions/alert-ec-ready.vue
  _dev/apps/ui/src/components/enhanced-conversions/alert-sign-gads-tos.vue
  _dev/apps/ui/src/components/enhanced-conversions/enhanced-conversions-card.spec.ts
  _dev/apps/ui/src/components/enhanced-conversions/enhanced-conversions-card.vue
  _dev/apps/ui/src/store/modules/app/getters-types.ts
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/store/modules/app/state.ts
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/views/debug-page.vue
Labels: Feature, VueJS

#1683 Add class material icon before rounded one
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/merchant-center-account/website-requirements/step-requirements.vue
  _dev/apps/ui/src/components/merchant-center-account/website-requirements/step-store-info.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
  _dev/apps/ui/src/components/product-feed/product-feed-card-report-card.vue
  _dev/apps/ui/src/components/product-feed/product-feed-card-report-products-card.vue
  _dev/apps/ui/src/components/product-feed/product-feed-card-report-products-sync-card.vue
  _dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-field.vue
  _dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
  _dev/apps/ui/src/components/product-feed/settings/commons/settings-footer.vue
  _dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/custom-carrier-form.vue
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: enhancement, VueJS

#1693 Hide introduction modal when feature flag is not enabled
  _dev/apps/ui/src/views/onboarding-page.vue
Labels: bug, VueJS

#1697 Add warning about potential failure of preview.js loading while opening storybook
  README.md
Labels: enhancement

#1702 Fix race condition while enabling conversion tags on configuration page
  _dev/apps/ui/src/components/campaigns/tracking-activation-modal.vue
Labels: bug, VueJS

#1701 EMKTG-3250: Move the register hooks function to the google connection
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/app/actions-types.ts
  _dev/apps/ui/src/store/modules/app/actions.ts
  _dev/apps/ui/src/views/onboarding-page.vue
  config.xml
  psxmarketingwithgoogle.php
Labels: bug, VueJS

#1670 Introduce monetization
  .gitignore
  _dev/apps/ui/.storybook/mock/ps-billing.ts
  _dev/apps/ui/.storybook/preview-head.html
  _dev/apps/ui/package.json
  _dev/apps/ui/src/App.vue
  _dev/apps/ui/src/assets/scss/abstracts/_variables.scss
  _dev/apps/ui/src/assets/scss/app.scss
  _dev/apps/ui/src/assets/scss/base/_typography.scss
  _dev/apps/ui/src/assets/scss/components/_cards.scss
  _dev/apps/ui/src/assets/scss/fonts/_material-icons.scss
  _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
  _dev/apps/ui/src/components/campaign/campaign-table-list.vue
  _dev/apps/ui/src/components/campaign/reporting/key-metrics/key-metrics-block.vue
  _dev/apps/ui/src/components/help/card-faq.vue
  _dev/apps/ui/src/components/onboarding/card-billing-connected.vue
  _dev/apps/ui/src/components/onboarding/onboarding-deps-container.vue
  _dev/apps/ui/src/components/onboarding/section-title.spec.ts
  _dev/apps/ui/src/components/onboarding/section-title.vue
  _dev/apps/ui/src/components/onboarding/two-panel-cols.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/submitted-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/panel/verified-products.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-page.vue
  _dev/apps/ui/src/components/product-feed/product-feed-settings.vue
  _dev/apps/ui/src/lib/billing.ts
  _dev/apps/ui/src/router/index.ts
  _dev/apps/ui/src/shims-tsx.d.ts
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/accounts/getters.ts
  _dev/apps/ui/src/store/modules/app/getters-types.ts
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/store/modules/app/state.ts
  _dev/apps/ui/src/views/billing-tab.vue
  _dev/apps/ui/src/views/debug-page.vue
  _dev/apps/ui/src/views/onboarding-page.vue
  _dev/apps/ui/stories/breadcrumb.stories.ts
  _dev/apps/ui/stories/onboarding-page.stories.ts
  _dev/apps/ui/stories/section-title.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
  _dev/pnpm-lock.yaml
  composer.json
  composer.lock
  config/common.yml
  config/common/billing.yml
  controllers/admin/AdminPsxMktgWithGoogleModuleController.php
  views/templates/admin/app.tpl
Labels: Feature, PHP, VueJS

#1705 Delete .github/release-drafter.yml
  .github/release-drafter.yml
Labels: enhancement

#1706 Update condition to display GMC badge
  _dev/apps/ui/.storybook/mock/merchant-center-account.ts
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/stories/merchant-center-account-card.stories.ts
Labels: bug, VueJS

#1704 Update readme with content about localization and releases
  README.md
Labels: documentation

#1708 Add a condition to display Subscription tab
  _dev/apps/ui/src/App.vue
Labels: bug, VueJS
