Repository PrestaShopCorp/psxmarketingwithgoogle, pull requests merged in 2024-01, with the labels that each got.

#1634 Update font sizes of product feed pages
  _dev/apps/ui/src/assets/scss/components/_badge.scss
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/status-card.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-row.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-row.vue
Labels: bug, VueJS

#1638 Improve responsiveness of product feed settings
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
Labels: enhancement, VueJS

#1639 Improve reactiveness on carriers form
  _dev/apps/ui/src/components/product-feed-page/dashboard/feed-configuration/feed-configuration-card.vue
  _dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.spec.ts
  _dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/shipping-settings.vue
  _dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/import-method/table-row-carrier.vue
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1635 Add root .htaccess
  .htaccess
Labels: enhancement, PHP

#1640 Introduce account errors reporting
  _dev/apps/ui/.storybook/mock/merchant-center-account.ts
  _dev/apps/ui/src/assets/scss/app.scss
  _dev/apps/ui/src/assets/scss/base/_border.scss
  _dev/apps/ui/src/assets/scss/components/_card-collapse.scss
  _dev/apps/ui/src/assets/scss/components/_modal.scss
  _dev/apps/ui/src/components/commons/card-collapse.spec.ts
  _dev/apps/ui/src/components/commons/card-collapse.vue
  _dev/apps/ui/src/components/merchant-center-account/issues/merchant-center-account-popin-account-issues.spec.ts
  _dev/apps/ui/src/components/merchant-center-account/issues/merchant-center-account-popin-account-issues.vue
  _dev/apps/ui/src/components/merchant-center-account/issues/types.ts
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed/settings/delivery-time-and-rates/estimate-method/countries-form-list.vue
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/accounts/getters.ts
  _dev/apps/ui/src/store/modules/accounts/mutations.ts
  _dev/apps/ui/src/store/modules/accounts/state.ts
  _dev/apps/ui/stories/base-buttons.stories.ts
  _dev/apps/ui/stories/merchant-center-account-card.stories.ts
  _dev/apps/ui/stories/merchant-center-account-popin-account-issues.stories.ts
  _dev/apps/ui/stories/product-feed-page/dashboard/product-feed-page.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1645 Introduce product issues + fix display of tooltips
  _dev/apps/ui/src/assets/scss/app.scss
  _dev/apps/ui/src/assets/scss/components/_google-issues.scss
  _dev/apps/ui/src/components/merchant-center-account/issues/merchant-center-account-popin-account-issues.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
  _dev/apps/ui/src/components/render-issues/account-issues.types.ts
  _dev/apps/ui/src/components/render-issues/collapsing-issues.spec.ts
  _dev/apps/ui/src/components/render-issues/collapsing-issues.vue
  _dev/apps/ui/src/components/render-issues/product-issues.types.ts
  _dev/apps/ui/src/components/render-issues/types.ts
  _dev/apps/ui/src/store/modules/accounts/state.ts
  _dev/apps/ui/stories/product-feed-page/disapproved-products-page/popin-product-issues.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1647 Update disapproved products table and plug with new product issues modal
  _dev/apps/ui/.storybook/mock/merchant-center-account.ts
  _dev/apps/ui/.storybook/mock/product-feed.ts
  _dev/apps/ui/.storybook/mock/product-feeds/validation/list.ts
  _dev/apps/ui/.storybook/mock/product-feeds/validation/product.ts
  _dev/apps/ui/src/components/commons/table-no-data.vue
  _dev/apps/ui/src/components/merchant-center-account/issues/merchant-center-account-popin-account-issues.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-alert-suspended.vue
  _dev/apps/ui/src/components/merchant-center-account/merchant-center-account-card.vue
  _dev/apps/ui/src/components/product-feed-page/dashboard/sync-overview.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-page.spec.ts
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-page.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-row.spec.ts
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-row.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/types.ts
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-details-page/non-compliant-products-details-page.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-page.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details-row.vue
  _dev/apps/ui/src/components/product-feed-page/product-feed-table-status-details.vue
  _dev/apps/ui/src/components/render-issues/account-issues.types.ts
  _dev/apps/ui/src/components/render-issues/collapsing-issues.spec.ts
  _dev/apps/ui/src/components/render-issues/collapsing-issues.vue
  _dev/apps/ui/src/components/render-issues/product-issues.types.ts
  _dev/apps/ui/src/components/render-issues/types.ts
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/accounts/getters.ts
  _dev/apps/ui/src/store/modules/accounts/state.ts
  _dev/apps/ui/src/store/modules/product-feed/actions-types.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/state.ts
  _dev/apps/ui/src/store/types.ts
  _dev/apps/ui/src/views/product-feed-page.vue
  _dev/apps/ui/stories/merchant-center-account-popin-account-issues.stories.ts
  _dev/apps/ui/stories/product-feed-page/disapproved-products-page/disapproved-products-page.stories.ts
  _dev/apps/ui/stories/product-feed-page/disapproved-products-page/popin-product-issues.stories.ts
  _dev/apps/ui/stories/product-feed-table-status-details.stories.ts
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: Feature, VueJS

#1650 Fix timezone param to get product issues
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1652 Do not display links when product is custom (not synced by us)
  _dev/apps/ui/.storybook/mock/product-feeds/validation/list.ts
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-row.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
Labels: bug, VueJS

#1653 Add a loading state while loading product issues
  _dev/apps/ui/src/components/commons/card-collapse-loading.vue
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
Labels: enhancement, VueJS

#1654 Display links as blocks
  _dev/apps/ui/src/assets/scss/components/_google-issues.scss
Labels: bug, VueJS

#1655 Add language filter selector on disapproved products
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/disapproved-products-page.vue
  _dev/apps/ui/src/components/product-feed-page/language-filter-selector.vue
  _dev/apps/ui/src/components/product-feed-page/non-compliant-products-page/non-compliant-products-page.vue
Labels: enhancement, VueJS

#1656 Open links to product pages in new tab
  _dev/apps/ui/src/components/product-feed-page/disapproved-products-page/popin-product-issues.vue
  _dev/packages/mktg-with-google-common/translations/en/ui.json
Labels: enhancement, VueJS

#1660 New Crowdin updates
  _dev/packages/mktg-with-google-common/translations/de/ui.json
  _dev/packages/mktg-with-google-common/translations/es/ui.json
  _dev/packages/mktg-with-google-common/translations/fr/ui.json
  _dev/packages/mktg-with-google-common/translations/it/ui.json
  _dev/packages/mktg-with-google-common/translations/nl/ui.json
  _dev/packages/mktg-with-google-common/translations/pl/ui.json
  _dev/packages/mktg-with-google-common/translations/pt/ui.json
  _dev/packages/mktg-with-google-common/translations/ro/ui.json
  _dev/packages/mktg-with-google-common/translations/ru/ui.json
Labels: waiting for dev

#1662 Set a limit when loading disapproved products
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1661 Make sure to send valid language codes
  _dev/apps/ui/src/lib/i18n.ts
  _dev/apps/ui/src/shims-tsx.d.ts
  _dev/apps/ui/src/store/modules/accounts/actions.ts
  _dev/apps/ui/src/store/modules/app/getters-types.ts
  _dev/apps/ui/src/store/modules/app/getters.ts
  _dev/apps/ui/src/store/modules/campaigns/actions.ts
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
  _dev/apps/warning-messages/src/index.ts
Labels: bug, VueJS

#1664 Set a limit when loading disapproved products
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1665 Fix request when limit must not be set
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS

#1667 Fix loading of issues for products without combinations
  _dev/apps/ui/src/store/modules/product-feed/actions.ts
Labels: bug, VueJS
